name: compile
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_HOME: ${{ github.workspace }}/work/.cargo-cache
  npm_config_cache: ${{ github.workspace }}/work/.npm-cache
  PACKAGER: "Turann_ <turanull000@gmail.com>"

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:base
    strategy:
      fail-fast: false
      matrix:
        package:
          - hid_t2magicmouse-dkms
          - t2bce-dkms
          - t2bdrm-dkms
          - t2gmux-dkms
          - t2mfi_fastcharge-dkms
          - t2touchbar-dkms
          - t2smc-dkms
          - t2smp-dkms
          - t2thunderbolt-dkms
          - t2sep-dkms
          - t2_precision_trackpad-dkms
          - t2_trackpad_actuator-dkms
          - kait2en-assets
          - t2-fan-control
          - t2-force-click
          - t2-smc-control
          - t2-journal
          - t2-power-tune
          - t2-power-explorer
          - t2-touchid
          - t2-cpu-control
          - t2-dgpu-control
          - t2-hybrid-gpu-control
          - t2-services
          - t2-ave
          - t2bce_audio-alsa-ucm-conf
          - t2bce_audio-dsp
          - react-drm
          - kait2en-modules-meta
          - kait2en-apps-meta

    steps:
      - name: Install build dependencies
        run: |
            pacman -Syu --noconfirm
            pacman -S --noconfirm --needed base-devel git rust npm nodejs python cargo gtk4 libadwaita glib2 glib2-devel gcc-libs pango cairo librsvg libdrm fprintd libfprint pipewire pipewire-audio pipewire-pulse wireplumber lsp-plugins-lv2 alsa-ucm-conf systemd python-gobject polkit bc cpio curl kmod msr-tools pciutils rsync brightnessctl cava

      - name: Checkout Arch Repo
        uses: actions/checkout@v7
        with:
          path: work/KaiT2en-Arch
          fetch-depth: 1

      - name: Checkout Shared KaiT2en-Fedora Cache
        uses: actions/checkout@v7
        with:
          repository: kaiT2en/KaiT2en-Fedora
          path: work/KaiT2en-Fedora
          fetch-depth: 1

      - name: Create non-root user
        run: |
          useradd -m turannul
          chown -R turannul:turannul work/

      - name: Build ${{ matrix.package }}
        run: su -p turannul -c "cd work/KaiT2en-Arch/${{ matrix.package }} && makepkg --nodeps --force"

      - name: Upload ${{ matrix.package }} artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.package }}
          path: work/KaiT2en-Arch/${{ matrix.package }}/*.pkg.tar.zst
          if-no-files-found: error
